# Generated by Django 4.2.7 on 2024-03-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_adduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adduser',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
